// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/paulohfera/todo-backend-go/configs"
	"github.com/paulohfera/todo-backend-go/internal/data/repository"
	repository2 "github.com/paulohfera/todo-backend-go/internal/domain/interface/repository"
	"github.com/paulohfera/todo-backend-go/internal/domain/usecase"
	"github.com/paulohfera/todo-backend-go/pkg/postgres"
)

// Injectors from wire.go:

func RegisterServicesUseCase() *usecase.TaskUseCase {
	configuration := configs.GetConfigurations()
	dbContext := db.NewOrGetSingleton(configuration)
	taskReposytory := repository.NewTaskReposytory(dbContext)
	taskUseCase := usecase.NewTaskUseCase(taskReposytory)
	return taskUseCase
}

// wire.go:

var providerSet wire.ProviderSet = wire.NewSet(db.NewOrGetSingleton, repository.NewTaskReposytory, usecase.NewTaskUseCase, wire.Bind(new(repository2.ITaskRepository), new(*repository.TaskReposytory)))
